### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by refekt** [refekt/Bot-Frost#104]
All you need to do is redesign the README with something more fitting for a college football oriented Discord bot. It can be generic and non-specific!

**Comment by ShishirPatil** [comment]
Assign me?

**Comment by abhinavjonnada82** [comment]
Can I get this?

**Comment by refekt** [comment]
Have at it

**Comment by abhinavjonnada82** [comment]
@refekt any specific thing you have on your mind. That I can add?

**Comment by refekt** [comment]
Nothing specific. As long as it's college football oriented and or GitHub page related

**Comment by refekt** [comment]
Thank you both! I have pulled your requests
