### ISSUE TITLE
make block 16 twitter feed for nota

### ISSUE THREAD

**Issue by hskrpwr** [refekt/Bot-Frost#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Mention**
@refekt

**Comment by refekt** [comment]
@hskrpwr can you elaborate a bit more if you have time. I'm opening this up for grabs

**Comment by ferociouskyle** [comment]
I'll take this. There isn't a way to re-assign this issue to me.

**Comment by refekt** [comment]
> I'll take this. There isn't a way to re-assign this issue to me. 

I'll try to assign

**Comment by refekt** [comment]
Actually this will have to move repos
