### ISSUE TITLE
Requesting a command

### ISSUE THREAD

**Issue by Mobius0ne** [refekt/Bot-Frost#128]
Requesting a command for Jojo Domann
$jojo brings up one of the following Jojo gifs
https://tenor.com/view/jo-jo-jo-jos-bizarre-adventure-joseph-joestar-anime-opening-gif-15084273
https://tenor.com/view/nice-joseph-joestar-jo-jos-bizarre-gif-13710213
https://tenor.com/view/joseph-joseph-joestar-anime-wink-gif-17972953
https://tenor.com/view/jotaro-kujo-jojo-bizarre-adventure-gif-14295795

**Comment by refekt** [comment]
Done
