### ISSUE TITLE
[BUG]  urban dictionary command is fucked

### ISSUE THREAD

**Issue by hskrpwr** [refekt/Bot-Frost#185]
**Describe the bug**
Shit's fucked

**To Reproduce**
Just try to use the command bitch

**Expected behavior**
The fucking command to fucking work

**Screenshots**
I'm not sending any pics until you pay me smh...

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
You wanted me to submit this ticket so here it is god damnit

**Comment by refekt** [comment]
Urban Dictionary changed their HTML. Borked the command. Fixed.
