### ISSUE TITLE
[REQUEST] DallE Mini Command

### ISSUE THREAD

**Issue by MartyChonks** [refekt/Bot-Frost#186]
**Describe the solution you'd like**
A /DallE (string) command, that will query the DallE Mini tool (https://huggingface.co/spaces/dalle-mini/dalle-mini) with the string provided and return the generated images.

**Comment by refekt** [comment]
I like this idea. Working on it now

**Comment by refekt** [comment]
Putting this on hold because I can't find a free version or a way to harvest that link you provided
